name: scRNA Benchmark (spaghetti)
id: spaghetti-plan
description: Benchmarking scRNA pipelines
benchmarker: "Atreya Choudhury"
version: "1.0.0"

software_backend: "conda"
software_environments:
  datasets_conda_env:
    name: datasets conda environment
    conda: envs/datasets-conda.yaml

stages:
  - id: datasets
    outputs:
      - id: data.h5ad
        path: "{dataset}.h5ad"
    modules:
      - id: datasets-r
        name: "loads scRNA datasets"
        software_environment: "datasets_conda_env"
        repository:
          url: https://github.com/scrna-bench/datasets
          commit: 53d94cb
        parameters:
          - dataset_name: "sc-mix"
