name: scRNA Benchmark (pipelines)
id: pipelines-plan
description: "Benchmarking scRNA pipelines (as implemented by Billato et al.: 10.1101/2025.10.28.681564)"
benchmarker: "Atreya Choudhury, Mark Robinson, Martin Emons, David Wissel"
version: "1.0.1"

software_backend: "apptainer"
software_environments:
  r_apptainer_env:
    name: datasets apptainer environment
    apptainer: envs/r-bioc-320-micro.sif
  pipelines-py_apptainer:
    name: pipelines-py apptainer environment
    apptainer: envs/scanpy_full.sif

stages:
  - id: datasets
    outputs:
      - id: data.h5ad
        path: "{dataset}.h5ad"
    modules:
      - id: datasets-r
        name: "loads scRNA datasets"
        software_environment: "r_apptainer_env"
        repository:
          url: https://github.com/scrna-bench/datasets
          commit: 411b717
        parameters:
          - dataset_name: "sc-mix"
  - id: methods
    inputs:
      - data.h5ad
    outputs:
      - id: timings.json
        path: "{dataset}.timings.json"
      - id: cluster.tsv
        path: "{dataset}.clusters.tsv"
      - id: pca.tsv
        path: "{dataset}.pca.tsv"
    modules:
      - id: pipelines-r
        name: "run r pipelines"
        software_environment: "r_apptainer_env"
        repository:
          url: https://github.com/scrna-bench/pipelines-r
          commit: main
        parameters:
          - method_name: ["seurat", "osca", "scrapper"]
      - id: pipelines-py
        name: "run python pipelines"
        software_environment: "pipelines-py_apptainer"
        repository:
          url: https://github.com/scrna-bench/pipelines-py
          commit: main
        parameters:
          - methods: ["scanpy", "rapids"]
