name: scRNA Benchmark (pipelines)
id: pipelines-plan
description: "Benchmarking scRNA pipelines (as implemented by Billato et al.: 10.1101/2025.10.28.681564)"
benchmarker: "Atreya Choudhury, Mark Robinson, Martin Emons, David Wissel"
version: "1.0.0"

software_backend: "conda"
software_environments:
  datasets_conda_env:
    name: datasets conda environment
    conda: envs/datasets-conda.yaml
  pipelines-r_conda_env:
    name: pipelines-r conda environment
    conda: envs/pipelines-r_conda_env.yaml
  pipelines-py_conda_env:
    name: pipelines-py conda environment
    conda: envs/pipelines-py_conda_env.yaml

stages:
  - id: datasets
    outputs:
      - id: data.h5ad
        path: "{dataset}.h5ad"
    modules:
      - id: datasets-r
        name: "loads scRNA datasets"
        software_environment: "datasets_conda_env"
        repository:
          url: https://github.com/scrna-bench/datasets
          commit: 1e7e34c
        parameters:
          - dataset_name: "sc-mix"
  - id: methods
    inputs:
      - data.h5ad
    outputs:
      - id: timings.json
        path: "{dataset}.timings.json"
      - id: cluster.tsv
        path: "{dataset}.cluster.tsv"
      - id: pca.tsv
        path: "{dataset}.pca.tsv"
    modules:
      - id: pipelines-r
        name: "run r pipelines"
        software_environment: "pipelines-r_conda_env"
        repository:
          url: https://github.com/scrna-bench/pipelines-r
          commit: main
        parameters:
          - methods: ["osca", "seurat", "scrapper", "seurat-sketch"]
      - id: pipeplines-py
        name: "run python pipelines"
        software_environment: "pipelines-py_conda_env"
        repository:
          url: https://github.com/scrna-bench/pipelines-py
          commit: main
        parameters:
          - methods: ["scanpy", "rapids"]
