name: scRNA Benchmark (pipelines)
id: pipelines-plan
description: "Benchmarking scRNA pipelines (as implemented by Billato et al.: 10.1101/2025.10.28.681564)"
benchmarker: "Atreya Choudhury, Mark Robinson, Martin Emons, David Wissel, Samuel Gunz"
version: "1.0.0"

software_backend: "apptainer"
software_environments:
  r_apptainer_env:
    name: datasets apptainer environment
    apptainer: oras://quay.io/omnibenchmark/scrna-bench:r-bioc-320-bf15bdde
  pipelines-py_apptainer:
    name: pipelines-py apptainer environment
    apptainer: envs/scanpy_full.sif
  #datasets_conda_env:
  #  name: datasets conda environment
  #  conda: envs/datasets-conda.yaml
  #pipelines-r_conda_env:
  #  name: pipelines-r conda environment
  #  conda: envs/pipelines-r_conda_env.yaml
#  pipelines-py_conda_env:
#    name: pipelines-py conda environment
#    conda: envs/pipelines-py_conda_env.yaml
#  metrics_conda_env:
#    name: metrics conda env
#    conda: envs/metrics_conda_env.yaml

stages:
  - id: datasets
    outputs:
      - id: data.h5ad
        path: "{dataset}.h5ad"
    modules:
      - id: datasets-r
        name: "loads scRNA datasets"
        software_environment: "r_apptainer_env"
        repository:
          url: https://github.com/scrna-bench/datasets
          commit: main
        parameters:
          - dataset_name: "sc-mix"
            #- dataset_name: ["sc-mix", "cb"]
  - id: methods
    inputs:
      - data.h5ad
    outputs:
      - id: timings.json
        path: "{dataset}.timings.json"
      - id: cluster.tsv
        path: "{dataset}.clusters.tsv"
      - id: pca.tsv
        path: "{dataset}.pca.tsv"
    modules:
      - id: pipelines-r
        name: "run r pipelines"
        software_environment: "r_apptainer_env"
        repository:
          url: https://github.com/scrna-bench/pipelines-r
          commit: e415d1f
        parameters:
          - method_name: ["seurat", "osca", "scrapper"]
      - id: pipelines-py
        name: "run python pipelines"
        software_environment: "pipelines-py_apptainer"
        repository:
          url: https://github.com/scrna-bench/pipelines-py
          commit: main
        parameters:
          - methods: ["scanpy"]
