name: scRNA Benchmark (pipelines)
id: pipelines-plan
description: Benchmarking scRNA pipelines
benchmarker: "Atreya Choudhury, Mark Robinson, Martin Emons, David Wissel"
version: "1.0.0"

software_backend: "conda"
software_environments:
  datasets_conda_env:
    name: datasets conda environment
    conda: envs/datasets-conda.yaml
  pipelines-r_conda_env:
    name: pipelines-r conda environment
    conda: envs/pipelines-r_conda_env.yaml
  pipelines-py_conda_env:
    name: pipelines-py conda environment
    conda: envs/pipelines-py_conda_env.yaml
  metrics_conda_env:
    name: metrics conda env
    conda: envs/metrics_conda_env.yaml

stages:
  - id: datasets
    outputs:
      - id: data.h5ad
        path: "{dataset}.h5ad"
    modules:
      - id: datasets-r
        name: "loads scRNA datasets"
        software_environment: "datasets_conda_env"
        repository:
          url: https://github.com/scrna-bench/datasets
          commit: 1e7e34c
        parameters:
          - dataset_name: "sc-mix"

  - id: metrics
    modules:
      - id: metrics
        name: "pipelines clustering metrics"
        software_environment: "metrics_conda_env"
        repository:
          url: https://github.com/scrna-bench/metrics
          commit: doloret
        parameters:
          - values: ["--metric", "adjusted_rand_score"]
    inputs:
      - entries:
          - cluster.tsv
          - data.h5ad
    outputs:
      - id: metrics.scores
        path: "{dataset}/{stage}/{module}/{param}/scores.json"
