name: scRNA Benchmark (pipelines)
id: pipelines-plan
description: "Benchmarking scRNA pipelines (as implemented by Billato et al.: 10.1101/2025.10.28.681564)"
benchmarker: "Atreya Choudhury, Mark Robinson, Martin Emons, David Wissel, Samuel Gunz"
version: "1.0.0"

software_backend: "apptainer"
software_environments:
  r_apptainer_env:
    name: datasets apptainer environment
    apptainer: oras://quay.io/omnibenchmark/scrna-bench:r-bioc-320-latest-amd64
  pipelines-py_apptainer:
    name: pipelines-py apptainer environment
    apptainer: oras://quay.io/omnibenchmark/scrna-bench:scanpy-latest-amd64
  #datasets_conda_env:
  #  name: datasets conda environment
  #  conda: envs/datasets-conda.yaml
  #pipelines-r_conda_env:
  #  name: pipelines-r conda environment
  #  conda: envs/pipelines-r_conda_env.yaml
#  pipelines-py_conda_env:
#    name: pipelines-py conda environment
#    conda: envs/pipelines-py_conda_env.yaml
#  metrics_conda_env:
#    name: metrics conda env
#    conda: envs/metrics_conda_env.yaml

metric_collectors:
  - id: report
    name: "Gathers and processes metrics from different pipelines"
    software_environment: "r_apptainer_env"
    repository:
      url: https://github.com/scrna-bench/pipelines-report
      commit: main
    inputs:
      - metrics.json
    outputs:
      - id: report.ari
        path: "report/ari.tsv"
      - id: report.timings
        path: "report/timings.tsv"

stages:
  - id: datasets
    outputs:
      - id: data.h5ad
        path: "{dataset}.h5ad"
      - id: data.clusters_truth
        path: "{dataset}.clusters_truth.tsv"
    modules:
      - id: datasets-r
        name: "loads scRNA datasets"
        software_environment: "r_apptainer_env"
        repository:
          url: https://github.com/scrna-bench/datasets
          commit: main
        parameters:
          - dataset_name: ["sc-mix", "be1", "cb"]
          # - dataset_name: ["sc-mix", "be1", "cb", "1.3m"]
  - id: methods
    inputs:
      - data.h5ad
    outputs:
      - id: timings.json
        path: "{dataset}.timings.json"
      - id: cluster.tsv
        path: "{dataset}.clusters.tsv"
      - id: pca.tsv
        path: "{dataset}.pca.tsv"
    modules:
      - id: pipelines-r
        name: "run r pipelines"
        software_environment: "r_apptainer_env"
        repository:
          url: https://github.com/scrna-bench/pipelines-r
          commit: main
        parameters:
          - method_name: ["seurat", "osca", "scrapper"]
            resolution: [0.1, 0.12, 0.14]
      - id: pipelines-py
        name: "run python pipelines"
        software_environment: "pipelines-py_apptainer"
        repository:
          url: https://github.com/scrna-bench/pipelines-py
          commit: main
        parameters:
          - method_name: ["scanpy"]
            resolution: [0.1, 0.12, 0.14]
  - id: metrics
    inputs:
      - data.clusters_truth
      - cluster.tsv
      - timings.json
    outputs:
      - id: metrics.json
        path: "{dataset}.metrics.json"
    modules:
      - id: metrics
        name: "compute metrics"
        software_environment: "r_apptainer_env"
        repository:
          url: https://github.com/scrna-bench/metrics
          commit: main
